### ISSUE TITLE
XSS Vulnerability v1.11.6

### ISSUE THREAD

**Issue by zxc7528064** [xpressengine/xpressengine#1157]
Hi ~ I find a XSS Vulnerability (Stored)
Version : 1.11.6
Author : Noth(沈彧璿)
Step 1 : login system
Step 2 : Click the "General" icon below
![12](https://user-images.githubusercontent.com/45315211/83340121-14f63600-a307-11ea-9393-690e9fdf5713.jpg)
Step 3: Insert the XSS test grammar on the "Footer script" on the right and save it.
![1](https://user-images.githubusercontent.com/45315211/83340145-47079800-a307-11ea-9fe3-8c630e25cbab.jpg)
Step 4 : Back to the front desk
![3](https://user-images.githubusercontent.com/45315211/83340159-728a8280-a307-11ea-8094-c1f3fb14c76e.jpg)

**Comment by YJSoft** [comment]
Hi, although this issue is old, I'm leaving comment since it's invalid.

1. This repo is for `XpressEngine3`, so codebase is completely different. You should leave issue at `xpressengine/xe-core`
2. That's not XSS issue, since only admins are allowed to edit those areas. (Actually you don't need `">` at all since there are no filering at all)
